FROM python:3.6
RUN pip install gunicorn google-python-cloud-debugger
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD . /code
WORKDIR /code
ENV FLASK_ENV=production
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 appstore:app
