"""empty message

Revision ID: 09a67fb07bcc
Revises: 20dc5856bc93
Create Date: 2018-06-24 22:22:18.669982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a67fb07bcc'
down_revision = '20dc5856bc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_likes_user_id'), 'user_likes', ['user_id'], unique=False)
    op.create_index('user_like_app_user_index', 'user_likes', ['app_id', 'user_id'], unique=True)
    op.create_foreign_key(None, 'user_likes', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_likes', type_='foreignkey')
    op.drop_index('user_like_app_user_index', table_name='user_likes')
    op.drop_index(op.f('ix_user_likes_user_id'), table_name='user_likes')
    # ### end Alembic commands ###
