"""app: add preview_image cache

Revision ID: 0c3a1cfa6af5
Revises: 89e32c02be56
Create Date: 2025-12-11 08:34:29.526881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3a1cfa6af5'
down_revision = '89e32c02be56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('preview_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_flags', type_='foreignkey')
    # ### end Alembic commands ###
