"""empty message

Revision ID: 20dc5856bc93
Revises: 86ddb5784dde
Create Date: 2018-06-20 11:57:30.284657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dc5856bc93'
down_revision = '86ddb5784dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('icon_large', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('icon_small', sa.String(), nullable=True))
    op.drop_column('apps', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('apps', 'icon_small')
    op.drop_column('apps', 'icon_large')
    # ### end Alembic commands ###
