"""Initial revision

Revision ID: 2c1963771462
Revises: 
Create Date: 2018-06-20 01:05:48.567026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1963771462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('colour', sa.String(length=6), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_app_type'), 'categories', ['app_type'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('collection_platforms_index', 'collections', ['platforms'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_collections_app_type'), 'collections', ['app_type'], unique=False)
    op.create_table('developers',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'app_id')
    )
    op.create_index(op.f('ix_user_likes_app_id'), 'user_likes', ['app_id'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('app_uuid', postgresql.UUID(), nullable=True),
    sa.Column('category_id', sa.String(length=24), nullable=True),
    sa.Column('companion_ios', sa.Text(), nullable=True),
    sa.Column('companion_android', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('developer_id', sa.String(length=24), nullable=True),
    sa.Column('hearts', sa.Integer(), nullable=True),
    sa.Column('image_large', sa.String(), nullable=True),
    sa.Column('image_small', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('timeline_enabled', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_uuid')
    )
    op.create_index(op.f('ix_apps_category_id'), 'apps', ['category_id'], unique=False)
    op.create_table('asset_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('screenshots', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('headers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('banner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_collection_app_platform_index', 'asset_collections', ['app_id', 'platform'], unique=True)
    op.create_table('category_banner_apps',
    sa.Column('category_id', sa.String(length=24), nullable=True),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='cascade')
    )
    op.create_table('collection_apps',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='cascade')
    )
    op.create_table('home_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_banners_app_id'), 'home_banners', ['app_id'], unique=False)
    op.create_index(op.f('ix_home_banners_app_type'), 'home_banners', ['app_type'], unique=False)
    op.create_table('locker_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locker_entries_user_id'), 'locker_entries', ['user_id'], unique=False)
    op.create_index('locker_entry_app_user_index', 'locker_entries', ['app_id', 'user_id'], unique=True)
    op.create_table('releases',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.Column('has_pbw', sa.Boolean(), nullable=True),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('js_md5', sa.String(length=32), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('compatibility', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_app_id'), 'releases', ['app_id'], unique=False)
    op.create_index('release_app_compatibility_index', 'releases', ['compatibility'], unique=False, postgresql_using='gin')
    op.create_table('binaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.String(length=24), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('sdk_major', sa.Integer(), nullable=True),
    sa.Column('sdk_minor', sa.Integer(), nullable=True),
    sa.Column('process_info_flags', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binaries')
    op.drop_index('release_app_compatibility_index', table_name='releases')
    op.drop_index(op.f('ix_releases_app_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index('locker_entry_app_user_index', table_name='locker_entries')
    op.drop_index(op.f('ix_locker_entries_user_id'), table_name='locker_entries')
    op.drop_table('locker_entries')
    op.drop_index(op.f('ix_home_banners_app_type'), table_name='home_banners')
    op.drop_index(op.f('ix_home_banners_app_id'), table_name='home_banners')
    op.drop_table('home_banners')
    op.drop_table('collection_apps')
    op.drop_table('category_banner_apps')
    op.drop_index('asset_collection_app_platform_index', table_name='asset_collections')
    op.drop_table('asset_collections')
    op.drop_index(op.f('ix_apps_category_id'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_user_likes_app_id'), table_name='user_likes')
    op.drop_table('user_likes')
    op.drop_table('developers')
    op.drop_index(op.f('ix_collections_app_type'), table_name='collections')
    op.drop_index('collection_platforms_index', table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_categories_app_type'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
