"""Create updated_at column in apps

Revision ID: 2fed26ea87ca
Revises: 3edc55c9f541
Create Date: 2026-01-26 17:47:49.770946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fed26ea87ca'
down_revision = '3edc55c9f541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_apps_updated_at'), 'apps', ['updated_at'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        UPDATE apps
        SET updated_at = (
            SELECT MAX(published_date)
            FROM releases
            WHERE releases.app_id = apps.id
        )
        WHERE EXISTS (
            SELECT 1
            FROM releases
            WHERE releases.app_id = apps.id
        )
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_updated_at'), table_name='apps')
    op.drop_column('apps', 'updated_at')
    # ### end Alembic commands ###
