"""Introduce app sorting columns

Revision ID: 3edc55c9f541
Revises: 0c3a1cfa6af5
Create Date: 2025-12-14 04:31:04.072470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edc55c9f541'
down_revision = '0c3a1cfa6af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('recent_hearts', sa.Float(), nullable=True))
    op.add_column('apps', sa.Column('random_weekly', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_apps_recent_hearts'), 'apps', ['recent_hearts'], unique=False)
    op.create_index(op.f('ix_apps_random_weekly'), 'apps', ['random_weekly'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_random_weekly'), table_name='apps')
    op.drop_index(op.f('ix_apps_recent_hearts'), table_name='apps')
    op.drop_column('apps', 'random_weekly')
    op.drop_column('apps', 'recent_hearts')
    # ### end Alembic commands ###
