"""empty message

Revision ID: 51a11af8f9ac
Revises: 248bf8d6d3b4
Create Date: 2018-06-20 07:03:37.234304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a11af8f9ac'
down_revision = '248bf8d6d3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_apps_app_uuid'), 'apps', ['app_uuid'], unique=False)
    op.drop_constraint('apps_app_uuid_key', 'apps', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('apps_app_uuid_key', 'apps', ['app_uuid'])
    op.drop_index(op.f('ix_apps_app_uuid'), table_name='apps')
    # ### end Alembic commands ###
