"""empty message

Revision ID: 5ba6bf37672b
Revises: 2c1963771462
Create Date: 2018-06-20 06:15:21.679901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ba6bf37672b'
down_revision = '2c1963771462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('icon', sa.String(), nullable=True))
    op.drop_column('apps', 'image_large')
    op.drop_column('apps', 'image_small')
    op.drop_column('apps', 'uuid')
    op.drop_column('releases', 'changelog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('changelog', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('image_small', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('image_large', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('apps', 'icon')
    # ### end Alembic commands ###
