"""empty message

Revision ID: 61321bb8e32d
Revises: 09a67fb07bcc
Create Date: 2018-06-26 00:16:38.576111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61321bb8e32d'
down_revision = '09a67fb07bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('visible', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'visible')
    # ### end Alembic commands ###
