"""Add creation time to user_likes

Revision ID: 705e61509d00
Revises: ec9b0b6d8795
Create Date: 2025-11-12 00:55:51.383857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705e61509d00'
down_revision = 'ec9b0b6d8795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_likes_created_at'), 'user_likes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_likes_created_at'), table_name='user_likes')
    op.drop_column('user_likes', 'created_at')
    # ### end Alembic commands ###
