"""Add Discourse topic ID

Revision ID: 89e32c02be56
Revises: c2c7be2e8835
Create Date: 2025-12-03 09:42:17.001613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e32c02be56'
down_revision = 'c2c7be2e8835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('discourse_topic_id', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE apps
        SET discourse_topic_id = 0
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'discourse_topic_id')
    # ### end Alembic commands ###
