"""empty message

Revision ID: b42fcf431ada
Revises: 5ba6bf37672b
Create Date: 2018-06-20 06:56:40.755744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42fcf431ada'
down_revision = '5ba6bf37672b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=24), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pebblekit3', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('companion_app_app_platform_index', 'companion_app', ['app_id', 'platform'], unique=True)
    op.create_index(op.f('ix_companion_app_app_id'), 'companion_app', ['app_id'], unique=False)
    op.drop_column('apps', 'companion_android')
    op.drop_column('apps', 'companion_ios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('companion_ios', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('apps', sa.Column('companion_android', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companion_app_app_id'), table_name='companion_app')
    op.drop_index('companion_app_app_platform_index', table_name='companion_app')
    op.drop_table('companion_app')
    # ### end Alembic commands ###
