"""Create available_archives table.

Revision ID: c2c7be2e8835
Revises: d820786671c8
Create Date: 2025-11-25 01:12:10.968397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c7be2e8835'
down_revision = 'd820786671c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_archives_created_at'), 'available_archives', ['created_at'], unique=False)
    op.create_index(op.f('ix_available_archives_id'), 'available_archives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_available_archives_id'), table_name='available_archives')
    op.drop_index(op.f('ix_available_archives_created_at'), table_name='available_archives')
    op.drop_table('available_archives')
    # ### end Alembic commands ###
