"""empty message

Revision ID: c4e0470dc040
Revises: 6e68426913c7
Create Date: 2018-06-26 04:13:19.268364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0470dc040'
down_revision = '6e68426913c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locker_entries', sa.Column('user_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_locker_entries_user_token'), 'locker_entries', ['user_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locker_entries_user_token'), table_name='locker_entries')
    op.drop_column('locker_entries', 'user_token')
    # ### end Alembic commands ###
