"""Add installs to apps

Revision ID: d820786671c8
Revises: 705e61509d00
Create Date: 2025-11-17 23:57:40.337316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd820786671c8'
down_revision = '705e61509d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('installs', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE apps AS ap
        SET installs = sub.count
        FROM (
            SELECT app_id, COUNT(*) AS count
            FROM locker_entries
            GROUP BY app_id
        ) AS sub
        WHERE ap.id = sub.app_id
    """)
    op.create_index(op.f('ix_apps_installs'), 'apps', ['installs'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_installs'), table_name='apps')
    op.drop_column('apps', 'installs')
    # ### end Alembic commands ###
